[package]
authors = ["Pandicon", "matym1"]
name = "stellar-guesser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
csv = "1.2.2"
eframe = { version = "0.22.0", features = [
	"accesskit",
	"default_fonts",
	"glow",
	"persistence",
] }
help = "0.0.0"
nalgebra = "0.32.2"
serde = {version = "1.0.164", features=["derive"]}
