[package]
name = "sg_credits"
version = "0.0.0"
edition = "2021"

[dependencies]
egui = { workspace = true }
include_dir = "0.7.4"
log = "0.4.14"
once_cell = "1.20.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
