[workspace]
members = ["*"]
exclude = ["target"]
resolver = "2"

[workspace.dependencies]
angle = "0.5.0"
eframe = "0.31"
egui = "0.31"
log = "0.4.14"
nalgebra = { version = "0.33.0", default-features = false, features = ["std"] }
rand = "0.8.5"
spherical_geometry = "0.3.0"
