name: Rust CI

on: pull_request

jobs:
    test-and-clippy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  components: 'clippy, rustfmt'
            - name: Run tests (main app)
              working-directory: app
              run: cargo test --all-features
            - name: Run clippy (main app)
              working-directory: app
              run: cargo clippy --all-targets --all-features -- -D warnings
            - name: Check formatting (main app)
              working-directory: app
              run: cargo fmt --all -- --check
            - name: Run tests (crates)
              working-directory: crates
              run: cargo test --all-features
            - name: Run clippy (crates)
              working-directory: crates
              run: cargo clippy --all-targets --all-features -- -D warnings
            - name: Check formatting (crates)
              working-directory: crates
              run: cargo fmt --all -- --check
